import Head from 'next/head';
import PrivateRoute from '@/App/hook/PrivateRoute';


export default function Home() {
  return (
    <PrivateRoute>
      <>
        <Head>
          <title>Mext Admin</title>
          <meta name="description" content="Generated by Mext Admin" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </>
    </PrivateRoute>
  );
}
